"""baseline_schema

Revision ID: f75d2362cf9f
Revises: 
Create Date: 2026-07-01 20:28:42.890951

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'f75d2362cf9f'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('users',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('email', sa.String(length=255), nullable=True),
    sa.Column('password_hash', sa.String(length=255), nullable=True),
    sa.Column('telegram_chat_id', sa.BigInteger(), nullable=True),
    sa.Column('telegram_username', sa.String(length=255), nullable=True),
    sa.Column('name', sa.String(length=255), nullable=True),
    sa.Column('age', sa.Integer(), nullable=True),
    sa.Column('height_cm', sa.Integer(), nullable=True),
    sa.Column('weight_kg', sa.Float(), nullable=True),
    sa.Column('sport_level', sa.String(length=50), nullable=True),
    sa.Column('goal_type', sa.String(length=50), nullable=True),
    sa.Column('goal_target', sa.String(length=255), nullable=True),
    sa.Column('coros_email', sa.String(length=255), nullable=True),
    sa.Column('coros_password', sa.String(length=255), nullable=True),
    sa.Column('last_coros_sync', sa.DateTime(), nullable=True),
    sa.Column('last_health_sync_at', sa.DateTime(), nullable=True),
    sa.Column('max_hr', sa.Integer(), nullable=True),
    sa.Column('max_credible_pace', sa.Float(), nullable=True),
    sa.Column('max_gps_jump_m', sa.Float(), nullable=True),
    sa.Column('min_hr_for_fast_pace', sa.Integer(), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('registered_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('email'),
    sa.UniqueConstraint('telegram_chat_id')
    )
    op.create_table('audit_events',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('event_type', sa.String(length=100), nullable=False),
    sa.Column('severity', sa.String(length=20), nullable=False),
    sa.Column('message', sa.Text(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.Column('ip_address', sa.String(length=45), nullable=True),
    sa.Column('metadata_json', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('audit_events', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_audit_events_created_at'), ['created_at'], unique=False)
        batch_op.create_index(batch_op.f('ix_audit_events_event_type'), ['event_type'], unique=False)
        batch_op.create_index(batch_op.f('ix_audit_events_user_id'), ['user_id'], unique=False)

    op.create_table('auth_tokens',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('token', sa.String(length=64), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('used_at', sa.DateTime(), nullable=True),
    sa.Column('expires_at', sa.DateTime(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('auth_tokens', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_auth_tokens_expires_at'), ['expires_at'], unique=False)
        batch_op.create_index(batch_op.f('ix_auth_tokens_token'), ['token'], unique=True)
        batch_op.create_index(batch_op.f('ix_auth_tokens_user_id'), ['user_id'], unique=False)

    op.create_table('daily_metrics',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.Column('date', sa.Date(), nullable=False),
    sa.Column('avg_sleep_hrv', sa.Float(), nullable=True),
    sa.Column('sleep_hrv_baseline', sa.Float(), nullable=True),
    sa.Column('sleep_hrv_sd', sa.Float(), nullable=True),
    sa.Column('rhr', sa.Integer(), nullable=True),
    sa.Column('tired_rate', sa.Integer(), nullable=True),
    sa.Column('training_load', sa.Float(), nullable=True),
    sa.Column('training_load_ratio', sa.Float(), nullable=True),
    sa.Column('performance', sa.Integer(), nullable=True),
    sa.Column('ati', sa.Float(), nullable=True),
    sa.Column('cti', sa.Float(), nullable=True),
    sa.Column('vo2max', sa.Float(), nullable=True),
    sa.Column('lthr', sa.Integer(), nullable=True),
    sa.Column('stamina_level', sa.Float(), nullable=True),
    sa.Column('ltsp', sa.Float(), nullable=True),
    sa.Column('stamina_level_7d', sa.Float(), nullable=True),
    sa.Column('synced_at', sa.DateTime(), nullable=True),
    sa.Column('recovery_pct', sa.Integer(), nullable=True),
    sa.Column('form_score', sa.Float(), nullable=True),
    sa.Column('load_impact', sa.Float(), nullable=True),
    sa.Column('intensity_trend', sa.Float(), nullable=True),
    sa.Column('sleep_hrv_interval_list', sa.Text(), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('user_id', 'date', name='uq_user_date')
    )
    with op.batch_alter_table('daily_metrics', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_daily_metrics_user_id'), ['user_id'], unique=False)

    op.create_table('deleted_trainings',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.Column('begin_ts', sa.DateTime(), nullable=False),
    sa.Column('total_distance_km', sa.Float(), nullable=True),
    sa.Column('avg_heart_rate', sa.Integer(), nullable=True),
    sa.Column('max_heart_rate', sa.Integer(), nullable=True),
    sa.Column('training_type', sa.String(length=50), nullable=True),
    sa.Column('duration_minutes', sa.Float(), nullable=True),
    sa.Column('avg_temperature', sa.Integer(), nullable=True),
    sa.Column('elevation_gain', sa.Integer(), nullable=True),
    sa.Column('avg_cadence', sa.Integer(), nullable=True),
    sa.Column('training_effect', sa.Float(), nullable=True),
    sa.Column('vo2max', sa.Float(), nullable=True),
    sa.Column('calories', sa.Integer(), nullable=True),
    sa.Column('avg_pace', sa.Float(), nullable=True),
    sa.Column('deleted_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('deleted_trainings', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_deleted_trainings_user_id'), ['user_id'], unique=False)

    op.create_table('training_sessions',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.Column('begin_ts', sa.DateTime(), nullable=True),
    sa.Column('total_distance_km', sa.Float(), nullable=True),
    sa.Column('avg_heart_rate', sa.Integer(), nullable=True),
    sa.Column('max_heart_rate', sa.Integer(), nullable=True),
    sa.Column('training_type', sa.String(length=50), nullable=True),
    sa.Column('segments_count', sa.Integer(), nullable=True),
    sa.Column('duration_minutes', sa.Float(), nullable=True),
    sa.Column('segments_json', sa.JSON(), nullable=True),
    sa.Column('hr_pace_series', sa.JSON(), nullable=True),
    sa.Column('avg_temperature', sa.Integer(), nullable=True),
    sa.Column('weather_code', sa.Integer(), nullable=True),
    sa.Column('elevation_gain', sa.Integer(), nullable=True),
    sa.Column('elevation_loss', sa.Integer(), nullable=True),
    sa.Column('suspect_flags', sa.JSON(), nullable=True),
    sa.Column('cleaning_log', sa.JSON(), nullable=True),
    sa.Column('avg_cadence', sa.Integer(), nullable=True),
    sa.Column('training_effect', sa.Float(), nullable=True),
    sa.Column('anaerobic_training_effect', sa.Float(), nullable=True),
    sa.Column('vo2max', sa.Float(), nullable=True),
    sa.Column('calories', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('training_sessions', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_training_sessions_user_id'), ['user_id'], unique=False)

    op.create_table('weight_measurements',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.Column('weight_kg', sa.Float(), nullable=False),
    sa.Column('measured_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('weight_measurements', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_weight_measurements_user_id'), ['user_id'], unique=False)

    op.create_table('training_feedback',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('session_id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.Column('rating', sa.Integer(), nullable=False),
    sa.Column('notes', sa.String(length=500), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['session_id'], ['training_sessions.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('training_feedback', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_training_feedback_session_id'), ['session_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_training_feedback_user_id'), ['user_id'], unique=False)

    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('training_feedback', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_training_feedback_user_id'))
        batch_op.drop_index(batch_op.f('ix_training_feedback_session_id'))

    op.drop_table('training_feedback')
    with op.batch_alter_table('weight_measurements', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_weight_measurements_user_id'))

    op.drop_table('weight_measurements')
    with op.batch_alter_table('training_sessions', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_training_sessions_user_id'))

    op.drop_table('training_sessions')
    with op.batch_alter_table('deleted_trainings', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_deleted_trainings_user_id'))

    op.drop_table('deleted_trainings')
    with op.batch_alter_table('daily_metrics', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_daily_metrics_user_id'))

    op.drop_table('daily_metrics')
    with op.batch_alter_table('auth_tokens', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_auth_tokens_user_id'))
        batch_op.drop_index(batch_op.f('ix_auth_tokens_token'))
        batch_op.drop_index(batch_op.f('ix_auth_tokens_expires_at'))

    op.drop_table('auth_tokens')
    with op.batch_alter_table('audit_events', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_audit_events_user_id'))
        batch_op.drop_index(batch_op.f('ix_audit_events_event_type'))
        batch_op.drop_index(batch_op.f('ix_audit_events_created_at'))

    op.drop_table('audit_events')
    op.drop_table('users')
    # ### end Alembic commands ###
